In [1]:
import preprocessing as prep
import processing as proc
import json
import os
import pickle
import glob

In [2]:
filter_params = {
    "filter_order": 2,
    "bandwidth": [4, 50],
    "type": "bandpass",
    "fs": 256,
    "output": "sos",
}

proc_config = {
    "sessions": [2, 12, 14, 21, 27, 28, 31, 39, 41, 42],
    "stages": ["baseline", "shared", "individual"],
    "min_freq": 4,
    "max_freq": 30,
    "channels": ["TP9", "TP10", "AF7", "AF8"],
    "bandfreqs": {
        "theta": [4, 8],
        "alpha": [8, 13],
        "beta": [13, 30],
        # "gamma": [30, 50],
    },
}

window_config = {"fs": 256, "winsz": 4, "ovlap": 0.5}

In [3]:
cwd = os.getcwd()

preprodata = prep.prepro(
    stages=proc_config["stages"], sessions=proc_config["sessions"], cwd=cwd, filter_params=filter_params
)

In [9]:
preprodata['p1']['shared']

Empty DataFrame
Columns: [Session, TP9, AF7, AF8, TP10]
Index: []

In [4]:
procdata = proc.process(
            preprodata=preprodata,
            stages=proc_config["stages"],
            sessions=proc_config["sessions"],
            min_freq=proc_config["min_freq"],
            max_freq=proc_config["max_freq"],
            fs=window_config["fs"],
            winsz=window_config["winsz"],
            ovlap=window_config["ovlap"],
            channels=proc_config["channels"],
        )

baseline 2
1024 512 0 <function normalize_by_baseline at 0x000001E561818540>

ValueError: negative dimensions are not allowed

In [ ]:
procdata['baseline']

,Session,Metric,Epoch,TP9_TP9_4-5 Hz,TP9_TP9_5-6 Hz,TP9_TP9_6-7 Hz,TP9_TP9_7-8 Hz,TP9_TP9_8-9 Hz,TP9_TP9_9-10 Hz,TP9_TP9_10-11 Hz,...,AF8_AF8_20-21 Hz,AF8_AF8_21-22 Hz,AF8_AF8_22-23 Hz,AF8_AF8_23-24 Hz,AF8_AF8_24-25 Hz,AF8_AF8_25-26 Hz,AF8_AF8_26-27 Hz,AF8_AF8_27-28 Hz,AF8_AF8_28-29 Hz,AF8_AF8_29-30 Hz
0,2,coh,1,0.321942,0.143060,0.191337,0.234231,0.205647,0.173429,0.156538,...,0.186087,0.170894,0.152643,0.134092,0.117730,0.105397,0.097995,0.095421,0.096869,0.101367
1,2,coh,2,0.388517,0.319585,0.269048,0.283864,0.241503,0.247711,0.205672,...,0.191052,0.169976,0.143288,0.114401,0.086892,0.063832,0.047203,0.037269,0.032129,0.029300
2,2,coh,3,0.326057,0.376321,0.352447,0.266325,0.219057,0.232118,0.206807,...,0.270750,0.247434,0.215528,0.180381,0.146469,0.117098,0.093882,0.076350,0.062647,0.052311
3,2,coh,4,0.470804,0.542049,0.532865,0.407996,0.301234,0.226663,0.185138,...,0.234909,0.216609,0.192354,0.167342,0.145599,0.129602,0.119961,0.115342,0.113406,0.112527
4,2,coh,5,0.158257,0.224019,0.331556,0.354824,0.334748,0.276652,0.227507,...,0.079779,0.081599,0.085806,0.094696,0.104540,0.110992,0.113469,0.112408,0.109013,0.104933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1755,42,wpli,40,0.464301,0.662081,0.492298,0.511443,0.391852,0.393404,0.351040,...,0.291640,0.298769,0.299570,0.294530,0.283856,0.268971,0.251801,0.234847,0.217925,0.201218
1756,42,wpli,41,0.517848,0.680487,0.529605,0.485501,0.360833,0.396247,0.402522,...,0.160105,0.173555,0.188811,0.206552,0.226841,0.248894,0.272031,0.295017,0.316538,0.336456
1757,42,wpli,42,0.788439,0.641000,0.703117,0.635373,0.464970,0.420978,0.329417,...,0.096083,0.097527,0.098216,0.099561,0.103232,0.110298,0.120920,0.134845,0.151807,0.172082
1758,42,wpli,43,0.905055,0.735008,0.716168,0.684068,0.522101,0.339979,0.281247,...,0.310360,0.300953,0.281521,0.255742,0.228200,0.203398,0.183116,0.167288,0.155001,0.144719
1759,42,wpli,44,0.225818,0.357447,0.364581,0.383207,0.254179,0.202557,0.164214,...,0.219897,0.207980,0.186933,0.159635,0.128291,0.096583,0.067978,0.043859,0.026068,0.023052

In [ ]:
band_procdata = proc.get_band_average(
    procdata=procdata,
    band_freqs=proc_config["bandfreqs"],
    stages=proc_config["stages"],
    channels=proc_config["channels"],
)

In [ ]:
band_procdata['baseline']

,Session,Metric,Epoch,TP9_TP9_theta,TP9_TP9_alpha,TP9_TP9_beta,TP9_TP10_theta,TP9_TP10_alpha,TP9_TP10_beta,TP9_AF7_theta,...,AF8_TP9_beta,AF8_TP10_theta,AF8_TP10_alpha,AF8_TP10_beta,AF8_AF7_theta,AF8_AF7_alpha,AF8_AF7_beta,AF8_AF8_theta,AF8_AF8_alpha,AF8_AF8_beta
0,2,coh,1,0.222642,0.175380,0.263167,0.337230,0.184619,0.246965,0.254971,...,0.169646,0.387542,0.202411,0.169643,0.247305,0.178926,0.163172,0.258088,0.262879,0.163416
1,2,coh,2,0.315254,0.209398,0.129853,0.322356,0.208585,0.153239,0.216074,...,0.154379,0.327967,0.289885,0.161858,0.206720,0.151812,0.176106,0.188424,0.267109,0.152685
2,2,coh,3,0.330287,0.219163,0.109423,0.342934,0.240811,0.113416,0.198999,...,0.197277,0.243708,0.157409,0.189279,0.171190,0.178605,0.219376,0.248391,0.154139,0.198557
3,2,coh,4,0.488428,0.215041,0.194281,0.369045,0.207788,0.196234,0.151847,...,0.192955,0.325149,0.187709,0.186336,0.148312,0.158698,0.187587,0.310632,0.154295,0.189353
4,2,coh,5,0.267164,0.253090,0.204448,0.327451,0.237751,0.205219,0.124296,...,0.092758,0.316228,0.153625,0.085225,0.120816,0.117433,0.121776,0.181337,0.096460,0.094089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1755,42,wpli,40,0.532531,0.312237,0.142074,0.579915,0.315569,0.152505,0.470712,...,0.241215,0.377870,0.278568,0.266066,0.443234,0.252603,0.289952,0.257588,0.229646,0.259915
1756,42,wpli,41,0.553360,0.367918,0.303554,0.457872,0.338256,0.300765,0.416802,...,0.198942,0.337354,0.266087,0.193175,0.268601,0.253756,0.191649,0.513955,0.232251,0.189772
1757,42,wpli,42,0.691982,0.387406,0.540174,0.511759,0.346382,0.534901,0.522001,...,0.109174,0.408652,0.297527,0.112374,0.569901,0.293221,0.115244,0.553050,0.236644,0.111026
1758,42,wpli,43,0.760075,0.374026,0.383377,0.415583,0.312176,0.381367,0.550378,...,0.234637,0.455520,0.217218,0.239347,0.470621,0.177077,0.238495,0.573827,0.192011,0.245791
1759,42,wpli,44,0.332763,0.159758,0.056428,0.260522,0.129073,0.043089,0.386093,...,0.149415,0.342250,0.127257,0.145213,0.493042,0.151553,0.139133,0.218181,0.140895,0.150854

In [ ]:
for state, df in band_procdata.items():
    df.to_csv(f'band_conndata_{state}.csv', index=False)